DROP TABLE audio_details IF EXISTS;

CREATE TABLE audio_details (
  recordId BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  userRecording VARCHAR(200),
  topicName VARCHAR(100),
  numberOfRecordings INT,
  reference VARCHAR(100),
  comments VARCHAR(100),
  source VARCHAR(100),


  PRIMARY KEY(recordId)
);
